# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancedetail',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='时间', verbose_name='时间'),
        ),
    ]
