# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 17:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_balancedetail_add_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(help_text='银行卡号', max_length=64, unique=True, verbose_name='银行卡号')),
                ('phone', models.CharField(blank=True, help_text='手机号', max_length=11, null=True, verbose_name='手机号')),
                ('name', models.CharField(blank=True, help_text='真实姓名', max_length=10, null=True, verbose_name='姓名')),
                ('id_card', models.CharField(blank=True, help_text='身份证', max_length=64, null=True, verbose_name='身份证')),
                ('card_type', models.CharField(blank=True, choices=[('DC', '借记卡'), ('CC', '信用卡'), ('SCC', '贷记卡'), ('DCC', '存贷合一卡'), ('PC', '预付卡'), ('STPB', '标准存折'), ('STFA', '标准对公账户'), ('NSTFA', '非标准对公账户')], help_text='银行卡类型', max_length=8, null=True, verbose_name='银行卡类型')),
                ('is_credit', models.BooleanField(default=True, help_text='是否是借记卡', verbose_name='是否是借记卡')),
                ('bank', models.CharField(blank=True, choices=[('SMS_76310006', '注册验证码'), ('SMS_76270012', '找回密码验证码')], help_text='银行', max_length=2, null=True, verbose_name='银行')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, help_text='添加时间', verbose_name='添加时间')),
                ('is_activate', models.BooleanField(default=True, help_text='是否激活', verbose_name='是否激活')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '银行卡表',
                'verbose_name_plural': '银行卡表',
                'ordering': ('-add_time',),
            },
        ),
        migrations.AlterModelOptions(
            name='balancedetail',
            options={'ordering': ('-add_time',), 'verbose_name': '账户余额变动表', 'verbose_name_plural': '账户余额变动表'},
        ),
    ]
