# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180524_1744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreditCard',
            new_name='BankCard',
        ),
    ]
