# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180822_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.CharField(choices=[('1', '待处理'), ('2', '提现完成'), ('3', '提现异常'), ('4', '已处理, 待银行打款')], default='1', help_text='提现状态', max_length=1, verbose_name='状态'),
        ),
    ]
