# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180525_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='card_type',
            field=models.CharField(blank=True, choices=[('DC', '储蓄卡'), ('CC', '信用卡'), ('SCC', '贷记卡'), ('DCC', '存贷合一卡'), ('PC', '预付卡'), ('STPB', '标准存折'), ('STFA', '标准对公账户'), ('NSTFA', '非标准对公账户')], help_text='银行卡类型', max_length=8, null=True, verbose_name='银行卡类型'),
        ),
    ]
