# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180525_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='card_no',
            field=models.CharField(help_text='银行卡号', max_length=64, verbose_name='银行卡号'),
        ),
    ]
