# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.CharField(choices=[('1', '待处理'), ('2', '提现完成'), ('3', '提现异常')], default='1', help_text='提现状态', max_length=1, verbose_name='状态'),
        ),
    ]
