# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180526_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithDrawDeal',
            fields=[
            ],
            options={
                'verbose_name': '待处理提现',
                'verbose_name_plural': '待处理提现',
                'proxy': True,
                'indexes': [],
            },
            bases=('accounts.withdraw',),
        ),
    ]
