# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20180529_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcematerial',
            name='subtitle',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='资源小标题'),
        ),
    ]
