# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20180529_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcematerial',
            options={'ordering': ('-weight', '-modify_time'), 'verbose_name': '资源文件', 'verbose_name_plural': '资源文件'},
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resource/category', verbose_name='主页图标'),
        ),
        migrations.AlterField(
            model_name='resourcematerial',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.ResourceCategory', verbose_name='所属分类'),
        ),
    ]
