"""
Django settings for MercenaryBackend project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys

from django.utils import timezone

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE_DIR)
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
sys.path.insert(0, os.path.join(BASE_DIR, 'extra_apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wiih3k9w*b!3gmu05g8s*387l5&z@*!ie5idka9w%)jn#!5o+%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
AUTH_USER_MODEL = 'users.ProfileInfo'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'xadmin',
    'crispy_forms',
    'django_filters',
    'rest_framework',
    'django_celery_results',
    'users.apps.UsersConfig',
    'area.apps.AreaConfig',
    'order.apps.OrderConfig',
    'paycenter.apps.PaycenterConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MercenaryBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MercenaryBackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "eros",
        'USER': 'eros',
        'PASSWORD': "tRFy7z8ht",
        'HOST': "127.0.0.1",
        'OPTIONS': {
            'autocommit': True,
            'init_command': 'SET default_storage_engine=INNODB',
            'charset': 'utf8mb4',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/
# 中文支持
LANGUAGE_CODE = 'zh-hans'
# 设置时区
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True
# 默认是Ture，时间是utc时间，由于我们要用本地时间，所用手动修改为false！！！！
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# 验证码过期时间
VERIFY_CODE_EXPIRE_TIME = 5 * 60
VERIFY_CODE_EXPIRE_TIME_DEFAULT = 5 * 60

# 注册短信有效期
REGEISTER_SMS_EXPIRE_TIME_DEFAULT = '5分钟'

# 验证后端
AUTHENTICATION_BACKENDS = (
    'users.views.CustomBackend',
)

# drf配置
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
#     ),
# }

# jwt配置
JWT_AUTH = {
    # token过期时间
    'JWT_EXPIRATION_DELTA': timezone.timedelta(days=1),
    'JWT_ALLOW_REFRESH': True,
}

# 阿里大于短信配置
SMS_ACCESS_KEY_ID = 'LTAISSYn8u9H4Q4u'
SMS_ACCESS_KEY_SECRET = 'rXFZmpAFgmiIUGxtaPW9Ron0nd8YQ4'

# 验证码类别
REGISTER_CODE_TYPE = 'SMS_76310006'
FORGET_PASSWD_CODE_TYPE = 'SMS_76270012'
CODE_TYPE = {
    REGISTER_CODE_TYPE: '注册验证码',
    FORGET_PASSWD_CODE_TYPE: '找回密码验证码',
}

# 阿里云oss相关配置
OSS_ACCESS_KEY_ID = 'LTAIgl1IpdAdgnJX'
OSS_ACCESS_KEY_SECRET = 'm5ohdxa6L04acDrYmauLRKbs69CTOC'
END_POINT = 'oss-cn-shenzhen.aliyuncs.com'
BUCKET_NAME = 'mercenary-user-up'
BUCKET_ACL_TYPE = 'public-read'

REDIS_HOST = '127.0.0.1'
REDIS_PORT = '6379'
REDIS_CELERY_BROKER_URL = '1'
REDIS_RESULT_BACKEND = '1'
REDIS_PASSWD = 'f886Yjhvuyfy76grhgdFYrtf'
REDIS_CONN_NOPASSWD = "redis://%s:%s/%s"
REDIS_CONN_WITHPASS = "redis://:%s@%s:%s/%s"

CELERY_BROKER_URL = REDIS_CONN_WITHPASS % (REDIS_PASSWD, REDIS_HOST, REDIS_PORT, REDIS_CELERY_BROKER_URL)
CELERY_RESULT_BACKEND = REDIS_CONN_WITHPASS % (REDIS_PASSWD, REDIS_HOST, REDIS_PORT, REDIS_RESULT_BACKEND)
CELERY_RESULT_SERIALIZER = 'pickle'
CELERY_TASK_SERIALIZER = 'pickle'
CELERY_ACCEPT_CONTENT = ['application/x-python-serialize']
CELERY_ENABLE_UTC = USE_TZ  # 不用UTC.
CELERY_TIMEZONE = TIME_ZONE  # 指定上海时区

# 日志配置
LOGGING = {
    'version': 1,
    # 使用True代表 默认配置中的所有logger 都将禁用，小心使用  一般都是Flase
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
        # 正常只使用下面这种
        'standard': {
            'format': '%(asctime)s [%(threadName)s:%(thread)d] [%(name)s:%(lineno)d] [%(module)s:%(funcName)s] [%(levelname)s %(message)s]'
        },
    },
    'filters': {
    },
    'handlers': {
        'null': {
            'level': 'DEBUG',
            'class': 'logging.NullHandler',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
        'default': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join("log", 'all.log'),
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter': 'standard',
        },
        'error': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join("log", 'error.log'),
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter': 'standard',
        },
        'request_handler': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join("log", 'script.log'),
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter': 'standard',
        },
        'scprits_handler': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join("log", 'script.log'),
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter': 'standard',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['default', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['request_handler'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'scripts': {
            'handlers': ['scprits_handler'],
            'level': 'INFO',
            'propagate': False,
        },
        'users.views': {
            'handlers': ['default', 'error'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'order.views': {
            'handlers': ['default', 'error'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'paycenter.views': {
            'handlers': ['default', 'error'],
            'level': 'DEBUG',
            'propagate': True,
        }
    }
}

# 项目的基本配置
# 手续费(百分制)
SERVICE_COST = 15

# 订单付款超时时间
PAY_DEFAULT_EXPIRE_TIME = 30 * 60
# 押金支付超时时间
PAY_DEPOSIT_EXPIRE_TIME = 5 * 60
# 佣兵点击完成到订单完成的时间间隔
PAY_COMPLETE_EXPIRE_TIME = 2 * 60 * 60
#####  支付相关  #####
ALIPAY_APPID = '2017080508049336'
ALIPAY_NOTIFY_URL = 'http://118.24.157.119:8000/alipay/return/'
ALIPAY_PRIVATE_KEY_PATH = '/www/MercenaryBackend/apps/utils/keys/private_2048.txt'
ALIPAY_ALI_PUBLIC_KEY_PATH = '/www/MercenaryBackend/apps/utils/keys/alipay_public_2048.txt'
ALIPAY_RETURN_URL = 'http://118.24.157.119:8000/alipay/return/'
ALIPAT_EXPIRE_TIME = 30 * 60
#####  支付相关  #####

try:
    from .local_settings import *
except:
    pass
