# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0005_auto_20180620_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='公司名称', max_length=128, verbose_name='公司名称')),
                ('telephone', models.CharField(blank=True, help_text='公司联系方式', max_length=20, null=True, verbose_name='公司联系方式')),
                ('introduce', models.TextField(blank=True, help_text='公司介绍', null=True, verbose_name='公司介绍')),
                ('logo', models.ImageField(blank=True, help_text='企业logo 现阶段是阿里云OSS地址', null=True, upload_to='company/logo', verbose_name='企业logo')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活', verbose_name='是否激活')),
                ('weight', models.IntegerField(default=1, verbose_name='权重')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, help_text='添加时间', verbose_name='添加时间')),
                ('address', models.ForeignKey(blank=True, help_text='公司地址', null=True, on_delete=django.db.models.deletion.CASCADE, to='area.Address', verbose_name='公司地址')),
            ],
        ),
    ]
