# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Browse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, help_text='浏览时间', verbose_name='浏览时间')),
            ],
            options={
                'verbose_name': '招募令浏览记录表',
                'verbose_name_plural': '招募令浏览记录表',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_start_time', models.DateTimeField(help_text='任务开始时间', null=True, verbose_name='任务开始时间')),
                ('task_end_time', models.DateTimeField(help_text='任务结束时间', null=True, verbose_name='任务结束时间')),
                ('sign_start_time', models.DateTimeField(help_text='报名开始时间', null=True, verbose_name='报名开始时间')),
                ('sign_end_time', models.DateTimeField(help_text='报名结束时间', null=True, verbose_name='报名结束时间')),
                ('min_num', models.PositiveSmallIntegerField(default=0, help_text='最少报名人数限制', verbose_name='最少报名人数限制')),
                ('max_num', models.PositiveSmallIntegerField(default=0, help_text='最多报名人数限制', verbose_name='最多报名人数限制')),
                ('sign_num', models.PositiveSmallIntegerField(default=0, help_text='报名人数', verbose_name='报名人数')),
                ('wages', models.PositiveIntegerField(default=0, help_text='工资/人均(分)', verbose_name='工资/人均(分)')),
                ('status', models.SmallIntegerField(choices=[(10, '任务审核中'), (11, '卡片报名中'), (20, '卡片报名完成'), (30, '卡片报名人数未达标'), (50, '卡片报名失败'), (51, '卡片退还押金中'), (60, '卡片结束')], help_text='卡片状态', verbose_name='卡片状态')),
            ],
            options={
                'verbose_name': '招募卡片表',
                'verbose_name_plural': '招募卡片表',
                'ordering': ('-task_start_time',),
            },
        ),
        migrations.CreateModel(
            name='CardSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, help_text='浏览时间', verbose_name='浏览时间')),
                ('status', models.SmallIntegerField(choices=[(10, '报名中'), (11, '报名押金支付中'), (12, '押金支付完成'), (13, '报名审核中'), (20, '报名成功'), (30, '任务进行中'), (40, '任务未完成'), (50, '任务已完成'), (60, '押金退换中')], help_text='报名状态', verbose_name='报名状态')),
            ],
            options={
                'verbose_name': '招募令卡片报名表',
                'verbose_name_plural': '招募令卡片报名表',
            },
        ),
        migrations.CreateModel(
            name='CardSignLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, help_text='备注', max_length=128, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, help_text='时间', verbose_name='时间')),
                ('sign', models.ForeignKey(help_text='报名记录', null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.CardSign', verbose_name='报名记录')),
            ],
            options={
                'verbose_name': '招募令卡片报名表',
                'verbose_name_plural': '招募令卡片报名表',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='公司名称', max_length=128, verbose_name='公司名称')),
                ('telephone', models.CharField(blank=True, help_text='公司联系方式', max_length=20, null=True, verbose_name='公司联系方式')),
                ('introduce', models.TextField(blank=True, help_text='公司介绍', null=True, verbose_name='公司介绍')),
                ('logo', models.ImageField(blank=True, help_text='企业logo 现阶段是阿里云OSS地址', null=True, upload_to='company/logo', verbose_name='企业logo')),
                ('weight', models.IntegerField(default=1, verbose_name='权重')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, help_text='添加时间', verbose_name='添加时间')),
                ('status', models.IntegerField(choices=[(10, '待认证'), (20, '认证中'), (30, '认证完成'), (50, '认证失败')], default=10, help_text='认证状态', verbose_name='认证状态')),
                ('address', models.ForeignKey(blank=True, help_text='公司地址', null=True, on_delete=django.db.models.deletion.CASCADE, to='area.Address', verbose_name='公司地址')),
            ],
            options={
                'verbose_name': '公司表',
                'verbose_name_plural': '公司表',
                'ordering': ('-weight',),
            },
        ),
        migrations.CreateModel(
            name='RecruitOrder',
            fields=[
                ('id', models.CharField(help_text='订单号', max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='订单号')),
                ('name', models.CharField(help_text='招募令标题', max_length=64, verbose_name='招募令标题')),
                ('task_start_time', models.DateTimeField(help_text='任务开始时间', null=True, verbose_name='任务开始时间')),
                ('task_end_time', models.DateTimeField(help_text='任务结束时间', null=True, verbose_name='任务结束时间')),
                ('sign_start_time', models.DateTimeField(help_text='报名开始时间', null=True, verbose_name='报名开始时间')),
                ('sign_end_time', models.DateTimeField(help_text='报名结束时间', null=True, verbose_name='报名结束时间')),
                ('commission', models.PositiveIntegerField(default=0, help_text='佣金', verbose_name='佣金')),
                ('need_deposit', models.BooleanField(default=True, help_text='是否需要佣兵缴纳押金', verbose_name='是否需要佣兵缴纳押金')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('detail', models.TextField(blank=True, help_text='详细信息', null=True, verbose_name='详细信息')),
                ('status', models.SmallIntegerField(choices=[(10, '审核中'), (11, '报名中'), (20, '报名完成'), (21, '任务完成'), (30, '报名人数未达标'), (50, '招募失败'), (51, '余额处理中'), (60, '招募令任务结束')], help_text='卡片状态', verbose_name='卡片状态')),
                ('weight', models.IntegerField(default=1, verbose_name='权重')),
                ('company', models.ForeignKey(help_text='所属公司', on_delete=django.db.models.deletion.CASCADE, to='recruit.Company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '招募令表',
                'verbose_name_plural': '招募令表',
                'ordering': ('-weight',),
            },
        ),
    ]
