# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='公司名称', max_length=128, verbose_name='公司名称')),
                ('telephone', models.CharField(blank=True, help_text='公司联系方式', max_length=20, null=True, verbose_name='公司联系方式')),
                ('introduce', models.TextField(blank=True, help_text='公司介绍', null=True, verbose_name='公司介绍')),
                ('logo', models.ImageField(blank=True, help_text='企业logo 现阶段是阿里云OSS地址', null=True, upload_to='company/logo', verbose_name='企业logo')),
                ('weight', models.IntegerField(default=1, verbose_name='权重')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, help_text='添加时间', verbose_name='添加时间')),
                ('status', models.IntegerField(choices=[(10, '待认证'), (20, '认证中'), (30, '认证完成'), (50, '认证失败')], default=10, help_text='认证状态', verbose_name='认证状态')),
            ],
            options={
                'verbose_name': '公司表',
                'verbose_name_plural': '公司表',
                'ordering': ('-weight',),
            },
        ),
    ]
