# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('-weight',), 'verbose_name': '公司表', 'verbose_name_plural': '公司表'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.IntegerField(choices=[(10, '待认证'), (20, '认证中'), (30, '认证完成'), (50, '认证失败')], default=10, help_text='认证状态', verbose_name='认证状态'),
        ),
    ]
