# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.ForeignKey(blank=True, help_text='公司地址', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Address', verbose_name='公司地址'),
        ),
    ]
