# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 13:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruit', '0001_initial'),
        ('area', '0002_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsignlog',
            name='user',
            field=models.ForeignKey(help_text='操作者', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作者'),
        ),
        migrations.AddField(
            model_name='cardsign',
            name='card',
            field=models.ForeignKey(help_text='卡片', on_delete=django.db.models.deletion.CASCADE, to='recruit.Card', verbose_name='卡片'),
        ),
        migrations.AddField(
            model_name='cardsign',
            name='user',
            field=models.ForeignKey(help_text='浏览者', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='浏览者'),
        ),
        migrations.AddField(
            model_name='card',
            name='address',
            field=models.ForeignKey(blank=True, help_text='任务地址', null=True, on_delete=django.db.models.deletion.CASCADE, to='area.Address', verbose_name='任务地址'),
        ),
        migrations.AddField(
            model_name='card',
            name='recruit',
            field=models.ForeignKey(help_text='所属招募令', on_delete=django.db.models.deletion.CASCADE, to='recruit.RecruitOrder', verbose_name='所属招募令'),
        ),
        migrations.AddField(
            model_name='browse',
            name='recruit',
            field=models.ForeignKey(help_text='浏览招募令', on_delete=django.db.models.deletion.CASCADE, to='recruit.RecruitOrder', verbose_name='浏览招募令'),
        ),
        migrations.AddField(
            model_name='browse',
            name='user',
            field=models.ForeignKey(help_text='浏览者', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='浏览者'),
        ),
        migrations.AlterUniqueTogether(
            name='cardsignlog',
            unique_together=set([('user', 'sign')]),
        ),
        migrations.AlterUniqueTogether(
            name='cardsign',
            unique_together=set([('user', 'card')]),
        ),
    ]
