# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 18:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruit', '0003_auto_20180718_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('message', models.TextField(blank=True, help_text='操作日志', null=True, verbose_name='操作日志')),
            ],
            options={
                'verbose_name': '公司认证日志表',
                'verbose_name_plural': '公司认证日志表',
                'ordering': ('-create_time',),
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('-weight', '-add_time'), 'verbose_name': '公司表', 'verbose_name_plural': '公司表'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AddField(
            model_name='companylog',
            name='company',
            field=models.ForeignKey(help_text='公司', on_delete=django.db.models.deletion.CASCADE, to='recruit.Company', verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='companylog',
            name='user',
            field=models.ForeignKey(help_text='操作者', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作者'),
        ),
    ]
