# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0005_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='remark',
            field=models.TextField(blank=True, help_text='公司认证申请备注信息', null=True, verbose_name='申请备注'),
        ),
    ]
