# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0005_auto_20180731_1717'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruit', '0006_company_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartTimeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='招募令标题', max_length=32, verbose_name='招募令标题')),
                ('description', models.TextField(blank=True, help_text='任务描述', null=True, verbose_name='任务描述')),
                ('requirement', models.TextField(blank=True, help_text='任务要求', null=True, verbose_name='任务要求')),
                ('wages', models.PositiveIntegerField(default=0, help_text='佣金/小时(单位:分)', verbose_name='佣金/小时(单位:分)')),
                ('settlement_method', models.CharField(choices=[('1', '日结'), ('2', '月结')], default='1', help_text='结算方式', max_length=2, verbose_name='结算方式')),
                ('deposit', models.PositiveIntegerField(default=0, help_text='招募令押金(单位:分)', verbose_name='招募令押金(单位:分)')),
                ('end_time', models.DateTimeField(blank=True, help_text='报名截止时间', null=True, verbose_name='报名截止时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('status', models.IntegerField(choices=[(10, '待审核'), (20, '进行中'), (30, '已完成'), (-10, '审核未通过'), (-20, '商户取消')], default=10, help_text='招募令状态', verbose_name='招募令状态')),
                ('weight', models.PositiveIntegerField(default=1, help_text='权重', verbose_name='权重')),
                ('enrol_total', models.PositiveIntegerField(default=0, help_text='报名人数', verbose_name='报名人数')),
                ('address_info', models.CharField(default='多地址可选', help_text='任务地址信息', max_length=128, verbose_name='任务地址信息')),
                ('company', models.ForeignKey(help_text='所属公司', on_delete=django.db.models.deletion.CASCADE, to='recruit.Company', verbose_name='所属公司')),
                ('liaison', models.ForeignKey(blank=True, help_text='对接负责人', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='对接负责人')),
            ],
            options={
                'verbose_name': '兼职招募令表',
                'verbose_name_plural': '兼职招募令表',
                'ordering': ('-weight', '-create_time'),
            },
        ),
        migrations.CreateModel(
            name='PartTimeOrderCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='任务开始时间', verbose_name='任务开始时间')),
                ('end_time', models.DateTimeField(help_text='任务结束时间', verbose_name='任务结束时间')),
                ('registration_deadline_time', models.DateTimeField(blank=True, help_text='报名截止时间', null=True, verbose_name='报名截止时间')),
                ('work_time', models.FloatField(default=0, help_text='工作时长', verbose_name='工作时长')),
                ('reward', models.PositiveIntegerField(default=0, help_text='预计佣金', verbose_name='预计佣金')),
                ('enrol_total', models.PositiveIntegerField(default=0, help_text='报名人数', verbose_name='报名人数')),
                ('enrol_count', models.PositiveIntegerField(default=0, help_text='需要人数', verbose_name='需要人数')),
                ('status', models.IntegerField(choices=[(10, '报名未开始'), (20, '报名中'), (30, '任务未开始'), (40, '进行中'), (50, '结算中'), (60, '已完成'), (-10, '商户取消')], default=10, help_text='状态', verbose_name='状态')),
                ('address', models.ForeignKey(help_text='任务地址', on_delete=django.db.models.deletion.CASCADE, to='area.Address', verbose_name='任务地址')),
                ('recruit', models.ForeignKey(help_text='所属招募令', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='recruit.PartTimeOrder', verbose_name='所属招募令')),
            ],
            options={
                'verbose_name': '兼职卡片',
                'verbose_name_plural': '兼职卡片',
                'ordering': ('start_time',),
            },
        ),
        migrations.CreateModel(
            name='PartTimeOrderCardSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '押金支付中'), (2, '商户审核中'), (11, '任务进行中'), (30, '已完成'), (-1, '押金支付超时取消'), (-10, '商户取消'), (-20, '用户取消')], default=1, help_text='状态', verbose_name='状态')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('reward', models.PositiveIntegerField(default=0, help_text='佣金', verbose_name='佣金')),
                ('card', models.ForeignKey(help_text='所属卡片', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='recruit.PartTimeOrderCard', verbose_name='所属卡片')),
                ('recruit', models.ForeignKey(help_text='所属招募令', on_delete=django.db.models.deletion.CASCADE, related_name='card_recruits', to='recruit.PartTimeOrder', verbose_name='所属招募令')),
            ],
            options={
                'verbose_name': '兼职卡片报名表',
                'verbose_name_plural': '兼职卡片报名表',
                'ordering': ('create_time',),
            },
        ),
        migrations.CreateModel(
            name='PartTimeOrderSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '押金支付中'), (11, '任务进行中'), (30, '已完成'), (-1, '押金支付超时取消'), (-10, '商户取消'), (-20, '用户取消')], default=1, help_text='状态', verbose_name='状态')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('recruit', models.ForeignKey(help_text='所属招募令', on_delete=django.db.models.deletion.CASCADE, related_name='recruits', to='recruit.PartTimeOrder', verbose_name='所属招募令')),
                ('user', models.ForeignKey(help_text='报名用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='报名用户')),
            ],
            options={
                'verbose_name': '兼职报名表',
                'verbose_name_plural': '兼职报名表',
                'ordering': ('create_time',),
            },
        ),
        migrations.AddField(
            model_name='parttimeordercardsignup',
            name='sign',
            field=models.ForeignKey(help_text='所属报名', on_delete=django.db.models.deletion.CASCADE, related_name='signs', to='recruit.PartTimeOrderSignUp', verbose_name='所属报名'),
        ),
        migrations.AddField(
            model_name='parttimeordercardsignup',
            name='user',
            field=models.ForeignKey(help_text='报名用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='报名用户'),
        ),
        migrations.AlterUniqueTogether(
            name='parttimeordersignup',
            unique_together=set([('user', 'recruit')]),
        ),
        migrations.AlterUniqueTogether(
            name='parttimeordercardsignup',
            unique_together=set([('user', 'card')]),
        ),
    ]
