# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0007_auto_20180920_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttimeorder',
            name='cust_mobile',
            field=models.CharField(blank=True, help_text='招募令联系人电话', max_length=15, null=True, verbose_name='招募令联系人电话'),
        ),
        migrations.AddField(
            model_name='parttimeorder',
            name='cust_username',
            field=models.CharField(blank=True, help_text='招募令联系人姓名', max_length=8, null=True, verbose_name='招募令联系人姓名'),
        ),
        migrations.AddField(
            model_name='parttimeordersignup',
            name='cust_mobile',
            field=models.CharField(blank=True, help_text='联系人电话', max_length=15, null=True, verbose_name='联系人电话'),
        ),
        migrations.AddField(
            model_name='parttimeordersignup',
            name='cust_sex',
            field=models.BooleanField(default=True, help_text='联系性别', verbose_name='联系人性别'),
        ),
        migrations.AddField(
            model_name='parttimeordersignup',
            name='cust_username',
            field=models.CharField(blank=True, help_text='联系人姓名', max_length=8, null=True, verbose_name='联系人姓名'),
        ),
    ]
