# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0007_parttimeorder_parttimeordercard_parttimeordercardsignup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parttimeorder',
            name='start_time',
        ),
        migrations.AddField(
            model_name='parttimeorder',
            name='address_info',
            field=models.CharField(blank=True, help_text='任务地址信息', max_length=128, null=True, verbose_name='任务地址信息'),
        ),
        migrations.AlterField(
            model_name='parttimeorder',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='报名截止时间', null=True, verbose_name='报名截止时间'),
        ),
        migrations.AlterField(
            model_name='parttimeorder',
            name='settlement_method',
            field=models.CharField(choices=[('1', '日结'), ('2', '月结')], default='1', help_text='结算方式', max_length=2, verbose_name='结算方式'),
        ),
    ]
