# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0008_auto_20180921_1808'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parttimeordercardsignup',
            unique_together=set([]),
        ),
    ]
