# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0008_auto_20180918_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttimeorder',
            name='address_info',
            field=models.CharField(default='多地址可选', help_text='任务地址信息', max_length=128, verbose_name='任务地址信息'),
        ),
    ]
