# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0009_auto_20180919_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttimeordercard',
            name='registration_deadline_time',
            field=models.DateTimeField(blank=True, help_text='报名截止时间', null=True, verbose_name='报名截止时间'),
        ),
        migrations.AlterField(
            model_name='parttimeordercardsignup',
            name='card',
            field=models.ForeignKey(help_text='所属卡片', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='recruit.PartTimeOrderCard', verbose_name='所属卡片'),
        ),
        migrations.AlterField(
            model_name='parttimeordercardsignup',
            name='status',
            field=models.IntegerField(choices=[(1, '押金支付中'), (2, '商户审核中'), (10, '任务未开始'), (11, '任务进行中'), (20, '结算中'), (30, '已完成'), (-1, '押金支付超时取消'), (-10, '商户取消'), (-20, '用户取消'), (-40, '旷工')], default=1, help_text='状态', verbose_name='状态'),
        ),
    ]
