# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruit', '0010_auto_20180919_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parttimeordercardsignup',
            options={'ordering': ('create_time',), 'verbose_name': '兼职报名表', 'verbose_name_plural': '兼职报名表'},
        ),
        migrations.AlterUniqueTogether(
            name='parttimeordercardsignup',
            unique_together=set([('user', 'card')]),
        ),
    ]
