# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 12:14
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, help_text='用户昵称 默认 用户+手机号后4位', max_length=30, verbose_name='用户昵称')),
                ('gender', models.NullBooleanField(help_text='未知时设置为 null', verbose_name='性别')),
                ('mobile', models.CharField(blank=True, help_text='手机号码', max_length=15, verbose_name='手机号码')),
                ('portrait', models.ImageField(blank=True, help_text='用户头像地址 现阶段是阿里云OSS地址', upload_to='portrait/%Y/%m/%d', verbose_name='头像')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(help_text='设备的唯一标识 mac地址 超过40位只保存40位', max_length=40, verbose_name='设备ID')),
                ('model', models.CharField(blank=True, help_text='类似于R9sPlus iPhone 6 等 超过20位只保存20位', max_length=20, verbose_name='设备型号')),
                ('device_ver', models.CharField(blank=True, help_text='设备的版本号 类似于 10.3.3 超过10位只保存10位', max_length=10, verbose_name='设备版本号')),
                ('channel_code', models.CharField(choices=[('1', 'ios'), ('2', 'android'), ('3', '微信公众号'), ('4', '微信小程序'), ('5', '支付宝小程序'), ('6', '快应用')], help_text='注册渠道 目前只支持 ios 和android', max_length=2, verbose_name='注册渠道号')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
        migrations.CreateModel(
            name='ProfileExtendInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='推荐人手机号')),
                ('rongcloud_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='融云IM Token')),
                ('jpush_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='极光推送Token')),
                ('balance', models.IntegerField(default=0, help_text='可用余额(分)', verbose_name='余额')),
                ('deposit_freeze', models.IntegerField(default=0, help_text='冻结金额(分)', verbose_name='冻结金额')),
                ('password', models.CharField(blank=True, help_text='支付密码(暂时不用)', max_length=128, null=True, verbose_name='支付密码')),
                ('remark', models.TextField(blank=True, help_text='备注信息', null=True, verbose_name='备注信息')),
                ('in_school', models.PositiveIntegerField(blank=True, help_text='所在学校/区域(外键)', verbose_name='所在学校/区域')),
                ('device_join', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.DeviceInfo', verbose_name='用户注册时的设备')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户扩展信息',
                'verbose_name_plural': '用户扩展信息',
            },
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SMS_76310006', '注册验证码'), ('SMS_76270012', '找回密码验证码')], help_text='验证码类型', max_length=12, verbose_name='验证码类别')),
                ('code', models.CharField(help_text='验证码', max_length=10, verbose_name='验证码')),
                ('mobile', models.CharField(help_text='手机号', max_length=11, verbose_name='手机号')),
                ('try_time', models.PositiveSmallIntegerField(default=3, help_text='默认3,当验证成功时删除,0时删除', verbose_name='剩余尝试次数')),
                ('expire_time', models.DateTimeField(default=django.utils.timezone.now, help_text='过期时间', verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '短信验证码',
                'verbose_name_plural': '短信验证码',
                'ordering': ['-expire_time'],
            },
        ),
    ]
