# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(help_text='设备的唯一标识 mac地址 超过40位只保存40位', max_length=40, verbose_name='设备ID')),
                ('model', models.CharField(blank=True, help_text='类似于R9sPlus iPhone 6 等 超过20位只保存20位', max_length=20, verbose_name='设备型号')),
                ('device_ver', models.CharField(blank=True, help_text='设备的版本号 类似于 10.3.3 超过10位只保存10位', max_length=10, verbose_name='设备版本号')),
                ('channel_code', models.CharField(help_text='注册渠道 目前只支持 ios 和android', max_length=2, verbose_name='注册渠道号')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
    ]
