# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180705_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileextendinfo',
            name='in_school',
            field=models.ForeignKey(blank=True, help_text='所在学校/区域(外键)', null=True, on_delete=django.db.models.deletion.CASCADE, to='area.School', verbose_name='所在学校/区域'),
        ),
    ]
