# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_deviceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileExtendInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_mobile', models.CharField(blank=True, max_length=15, verbose_name='推荐人手机号')),
                ('rongcloud_token', models.CharField(blank=True, max_length=100, verbose_name='融云IM Token')),
                ('jpush_token', models.CharField(blank=True, max_length=100, verbose_name='极光推送Token')),
                ('device_join', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.DeviceInfo', verbose_name='用户注册时的设备')),
            ],
            options={
                'verbose_name': '用户扩展信息',
                'verbose_name_plural': '用户扩展信息',
            },
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='mobile',
            field=models.CharField(blank=True, help_text='用户手机号', max_length=15, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='用户昵称 默认 用户+手机号后4位', max_length=30, verbose_name='用户昵称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='portrait',
            field=models.CharField(blank=True, default='', help_text='用户头像地址 现阶段是阿里云OSS地址', max_length=254, verbose_name='头像'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileextendinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
