# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180718_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileextendinfo',
            name='admin_company',
            field=models.ForeignKey(blank=True, help_text='企业用户', null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Company', verbose_name='企业用户'),
        ),
        migrations.AlterField(
            model_name='profileextendinfo',
            name='admin_school',
            field=models.ForeignKey(blank=True, help_text='管理学校/区域(外键)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_school', to='area.School', verbose_name='管理学校/区域'),
        ),
    ]
