# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180322_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4, verbose_name='验证码类别')),
                ('code', models.CharField(max_length=10, verbose_name='验证码')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('try_time', models.PositiveSmallIntegerField(default=3, help_text='默认3,当验证成功时删除,0时删除', verbose_name='剩余尝试次数')),
                ('expire_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '短信验证码',
                'verbose_name_plural': '短信验证码',
            },
        ),
    ]
