# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180911_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileextendinfo',
            name='wechat_number',
            field=models.CharField(blank=True, help_text='微信号', max_length=64, null=True, verbose_name='微信号'),
        ),
    ]
