# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_verifycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='type',
            field=models.CharField(choices=[('SMS_76310006', '注册验证码'), ('SMS_76270012', '找回密码验证码')], max_length=12, verbose_name='验证码类别'),
        ),
    ]
