# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180323_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='portrait',
            field=models.URLField(blank=True, help_text='用户头像地址 现阶段是阿里云OSS地址', max_length=254, verbose_name='头像'),
        ),
    ]
