# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180408_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='portrait',
            field=models.CharField(blank=True, help_text='用户头像地址 现阶段是阿里云OSS地址', max_length=254, verbose_name='头像'),
        ),
    ]
