# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180522_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='portrait',
            field=models.ImageField(blank=True, help_text='用户头像地址 现阶段是阿里云OSS地址', upload_to='', verbose_name='头像'),
        ),
    ]
