# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0003_school'),
        ('users', '0011_auto_20180529_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileextendinfo',
            name='admin_school',
            field=models.ForeignKey(blank=True, help_text='管理的学校', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_school', to='area.School', verbose_name='管理的学校'),
        ),
        migrations.AddField(
            model_name='profileextendinfo',
            name='in_school',
            field=models.ForeignKey(blank=True, help_text='属于学校', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_school', to='area.School', verbose_name='属于学校'),
        ),
    ]
