# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 14:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='大分类', max_length=255, verbose_name='大分类')),
                ('weight', models.IntegerField(default=1, help_text='权重', validators=[django.core.validators.MinValueValidator(1, message='不能小于%(limit_value)s.'), django.core.validators.MaxValueValidator(100, message='不能大于%(limit_value)s.')], verbose_name='权重')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活', verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '订单一级分类',
                'verbose_name_plural': '订单一级分类',
                'ordering': ['weight'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='小分类', max_length=255, verbose_name='小分类')),
                ('weight', models.IntegerField(default=1, help_text='权重', validators=[django.core.validators.MinValueValidator(1, message='不能小于%(limit_value)s.'), django.core.validators.MaxValueValidator(100, message='不能大于%(limit_value)s.')], verbose_name='权重')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活', verbose_name='是否激活')),
                ('classification', models.ForeignKey(help_text='所属分类', on_delete=django.db.models.deletion.CASCADE, to='order.Classification', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '订单二级分类',
                'verbose_name_plural': '订单二级分类',
                'ordering': ['weight'],
            },
        ),
    ]
