# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 11:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.CharField(help_text='订单号', max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='订单号')),
                ('status', models.SmallIntegerField(choices=[(1, '待付佣金'), (2, '佣金支付中'), (11, '待接单'), (12, '待付押金'), (13, '押金支付中'), (20, '任务进行中'), (21, '佣兵已确认'), (22, '雇主已确认'), (41, '待雇主评价(暂不使用)'), (42, '待佣兵评价(暂不使用)'), (50, '订单已完成'), (-11, '雇主申请取消'), (-12, '雇主主动取消'), (-13, '佣兵申请取消'), (-14, '佣兵主动取消'), (-15, '客服操作取消'), (-21, '佣金支付超时取消'), (-22, '押金支付超时取消(不使用)'), (-23, '接单超时取消')], default=1, help_text='订单状态', verbose_name='订单状态')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='订单创建时间', verbose_name='订单创建时间')),
                ('complete_time', models.DateTimeField(help_text='订单完成时间', null=True, verbose_name='订单完成时间')),
                ('privacy', models.TextField(help_text='订单隐私信息', null=True, verbose_name='订单隐私信息')),
                ('remark', models.TextField(help_text='订单备注信息', null=True, verbose_name='订单备注信息')),
                ('detail', models.TextField(help_text='订单详细信息', null=True, verbose_name='订单详细信息')),
                ('description', models.CharField(help_text='订单简短描述', max_length=255, null=True, verbose_name='订单简短描述')),
                ('deposit', models.PositiveSmallIntegerField(default=0, help_text='押金(分)', verbose_name='押金')),
                ('reward', models.PositiveSmallIntegerField(default=1, help_text='佣兵应得赏金(分)', verbose_name='佣金')),
                ('pay_cost', models.PositiveSmallIntegerField(default=1, help_text='雇主实付金额(分)', verbose_name='实付金额')),
                ('employer_receive_name', models.CharField(help_text='联系人姓名', max_length=30, null=True, verbose_name='联系人姓名')),
                ('employer_receive_mobile', models.CharField(help_text='联系人手机号', max_length=15, null=True, verbose_name='联系人手机号')),
                ('employer_complete_time', models.DateTimeField(help_text='雇主确认完成时间', null=True, verbose_name='雇主确认完成时间')),
                ('receiver_confirm_time', models.DateTimeField(help_text='佣兵接单时间', null=True, verbose_name='佣兵接单时间')),
                ('receiver_complete_time', models.DateTimeField(help_text='佣兵确认完成时间', null=True, verbose_name='佣兵确认完成时间')),
                ('from_addr_name', models.CharField(help_text='订单开始的点信息', max_length=32, null=True, verbose_name='订单开始的点信息')),
                ('from_addr_detail', models.CharField(help_text='订单开始的具体地址', max_length=64, null=True, verbose_name='订单开始的具体地址')),
                ('to_addr_name', models.CharField(help_text='订单结束的点信息', max_length=128, null=True, verbose_name='订单结束的点信息')),
                ('to_addr_detail', models.CharField(help_text='订单结束的具体地址', max_length=128, null=True, verbose_name='订单结束的具体地址')),
                ('from_time', models.DateTimeField(help_text='订单开始时间', null=True, verbose_name='订单开始时间')),
                ('to_time', models.DateTimeField(help_text='订单结束时间', null=True, verbose_name='订单结束时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='OrderOperateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('message', models.TextField(blank=True, help_text='操作日志', null=True, verbose_name='操作日志')),
                ('order', models.ForeignKey(blank=True, help_text='所属订单', null=True, on_delete=django.db.models.deletion.CASCADE, to='order.OrderInfo', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单日志',
                'verbose_name_plural': '订单日志',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='二级分类', max_length=255, verbose_name='分类名')),
                ('weight', models.IntegerField(default=1, help_text='权重', validators=[django.core.validators.MinValueValidator(1, message='不能小于%(limit_value)s.'), django.core.validators.MaxValueValidator(100, message='不能大于%(limit_value)s.')], verbose_name='权重')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活', verbose_name='是否激活')),
                ('classification', models.PositiveSmallIntegerField(choices=[(1, '即时'), (2, '顺风'), (3, '替身'), (4, '技能'), (5, '活动')], default=1, help_text='所属分类', verbose_name='父分类')),
                ('template', models.PositiveSmallIntegerField(choices=[(1, '描述'), (2, '商品'), (3, '快递')], default=1, help_text='分类数据所使用的模板', verbose_name='分类模板')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['-weight'],
            },
        ),
    ]
