# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(help_text='订单号', max_length=30, unique=True, verbose_name='订单号')),
                ('order_status', models.SmallIntegerField(choices=[(1, '待付赏金'), (2, '赏金支付中'), (11, '待接单'), (12, '待付押金'), (13, '押金支付中'), (20, '任务进行中'), (21, '佣兵已确认'), (22, '雇主已确认'), (41, '待雇主评价(暂不使用)'), (42, '待佣兵评价(暂不使用)'), (50, '订单已完成'), (-11, '雇主申请取消'), (-12, '雇主主动取消'), (-13, '佣兵申请取消'), (-14, '佣兵主动取消'), (-15, '客服操作取消'), (-21, '赏金支付超时取消'), (-22, '押金支付超时取消')], default=1, verbose_name='订单状态')),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now, help_text='订单创建时间', verbose_name='订单创建时间')),
                ('order_finish_time', models.DateTimeField(default=django.utils.timezone.now, help_text='订单完成时间', verbose_name='订单完成时间')),
                ('deposit', models.PositiveSmallIntegerField(default=0, help_text='押金(分)', verbose_name='押金')),
                ('reward', models.PositiveSmallIntegerField(default=1, help_text='佣兵应得赏金(分)', verbose_name='赏金')),
                ('pay_cost', models.PositiveSmallIntegerField(default=1, help_text='雇主实付金额(分)', verbose_name='实付金额')),
                ('employer_receive_name', models.CharField(help_text='联系人姓名', max_length=30, verbose_name='联系人姓名')),
                ('employer_receive_mobile', models.CharField(help_text='联系人手机号', max_length=11, verbose_name='联系人手机号')),
                ('employer_complete_time', models.DateTimeField(help_text='雇主确认完成时间', null=True, verbose_name='雇主确认完成时间')),
                ('receiver_confirm_time', models.DateTimeField(help_text='佣兵接单时间', null=True, verbose_name='佣兵接单时间')),
                ('receiver_complete_time', models.DateTimeField(help_text='佣兵确认完成时间', null=True, verbose_name='佣兵确认完成时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='classification',
            field=models.PositiveSmallIntegerField(choices=[(1, '即时'), (2, '顺风'), (3, '替身'), (4, '技能'), (5, '活动')], default=1, help_text='所属分类', verbose_name='父分类'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='template',
            field=models.PositiveSmallIntegerField(choices=[(1, '描述'), (2, '商品'), (3, '快递')], default=1, help_text='分类数据所使用的模板', verbose_name='分类模板'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='category',
            field=models.ForeignKey(help_text='订单分类', on_delete=django.db.models.deletion.CASCADE, to='order.SubCategory', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='employer_user',
            field=models.ForeignKey(help_text='雇主', on_delete=django.db.models.deletion.CASCADE, related_name='employer_user', to=settings.AUTH_USER_MODEL, verbose_name='雇主'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='receiver_user',
            field=models.ForeignKey(help_text='佣兵', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to=settings.AUTH_USER_MODEL, verbose_name='佣兵'),
        ),
    ]
