# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'ordering': ('-create_time',), 'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待付赏金'), (2, '赏金支付中'), (11, '待接单'), (12, '待付押金'), (13, '押金支付中'), (20, '任务进行中'), (21, '佣兵已确认'), (22, '雇主已确认'), (41, '待雇主评价(暂不使用)'), (42, '待佣兵评价(暂不使用)'), (50, '订单已完成'), (-11, '雇主申请取消'), (-12, '雇主主动取消'), (-13, '佣兵申请取消'), (-14, '佣兵主动取消'), (-15, '客服操作取消'), (-21, '赏金支付超时取消'), (-22, '押金支付超时取消'), (-23, '接单超时取消')], default=1, help_text='订单状态', verbose_name='订单状态'),
        ),
    ]
