# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_auto_20180419_0916'),
        ('order', '0002_auto_20180423_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='order_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='order_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='order_finish_time',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='order_sn',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='complete_time',
            field=models.DateTimeField(help_text='订单完成时间', null=True, verbose_name='订单完成时间'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='create_addrname',
            field=models.CharField(help_text='订单创建的具体地址', max_length=128, null=True, verbose_name='订单创建的具体地址'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='create_district',
            field=models.ForeignKey(help_text='订单创建的城市', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_district', to='area.District', verbose_name='订单创建的城市'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='description',
            field=models.CharField(help_text='订单简短描述', max_length=255, null=True, verbose_name='订单简短描述'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='detail',
            field=models.TextField(help_text='订单详细信息', null=True, verbose_name='订单详细信息'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='from_addrname',
            field=models.CharField(help_text='订单开始的具体地址', max_length=128, null=True, verbose_name='订单开始的具体地址'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='from_district',
            field=models.ForeignKey(help_text='订单开始的城市', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_district', to='area.District', verbose_name='订单开始的城市'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='from_time',
            field=models.DateTimeField(help_text='订单开始时间', null=True, verbose_name='订单开始时间'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='privacy',
            field=models.TextField(help_text='订单隐私信息', null=True, verbose_name='订单隐私信息'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='remark',
            field=models.TextField(help_text='订单备注信息', null=True, verbose_name='订单备注信息'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='to_addrname',
            field=models.CharField(help_text='订单结束的具体地址', max_length=128, null=True, verbose_name='订单结束的具体地址'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='to_district',
            field=models.ForeignKey(help_text='订单结束的城市', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_district', to='area.District', verbose_name='订单结束的城市'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='to_time',
            field=models.DateTimeField(help_text='订单结束时间', null=True, verbose_name='订单结束时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='employer_receive_mobile',
            field=models.CharField(help_text='联系人手机号', max_length=15, verbose_name='联系人手机号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='id',
            field=models.CharField(help_text='订单号', max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='订单号'),
        ),
    ]
