# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0003_school'),
        ('order', '0003_auto_20180518_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='school',
            field=models.ForeignKey(blank=True, help_text='学院', null=True, on_delete=django.db.models.deletion.CASCADE, to='area.School', verbose_name='学校'),
        ),
    ]
