# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20180723_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='图片', null=True, upload_to='', verbose_name='图片')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '订单图片',
                'verbose_name_plural': '订单图片',
            },
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, '即时'), (2, '顺风'), (3, '替身'), (4, '技能'), (5, '活动')], default=1, help_text='所属分类', verbose_name='所属分类'),
        ),
        migrations.AddField(
            model_name='ordersimage',
            name='order',
            field=models.ForeignKey(help_text='所属订单', on_delete=django.db.models.deletion.CASCADE, to='order.OrderInfo', verbose_name='所属订单'),
        ),
    ]
