# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20180723_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='create_district',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='from_addr_detail',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='from_addr_name',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='to_addr_detail',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='to_addr_name',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='from_addr',
            field=models.CharField(help_text='任务地点', max_length=128, null=True, verbose_name='任务地点'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='to_addr',
            field=models.CharField(help_text='交付地点', max_length=128, null=True, verbose_name='交付地点'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='description',
            field=models.TextField(help_text='订单详细信息', null=True, verbose_name='订单详细信息'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='from_time',
            field=models.DateTimeField(help_text='任务开始时间', null=True, verbose_name='任务开始时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='school',
            field=models.ForeignKey(help_text='订单所在学校', on_delete=django.db.models.deletion.CASCADE, to='area.School', verbose_name='订单所在学校'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='to_time',
            field=models.DateTimeField(help_text='任务结束时间', null=True, verbose_name='任务结束时间'),
        ),
        migrations.AlterField(
            model_name='ordersimage',
            name='image',
            field=models.ImageField(blank=True, help_text='图片', null=True, upload_to='order/%Y/%m/%d', verbose_name='图片'),
        ),
    ]
