# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20180803_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='school',
            field=models.ForeignKey(help_text='订单所在学校', null=True, on_delete=django.db.models.deletion.CASCADE, to='area.School', verbose_name='订单所在学校'),
        ),
        migrations.AlterField(
            model_name='ordersimage',
            name='order',
            field=models.ForeignKey(help_text='所属订单', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='order.OrderInfo', verbose_name='所属订单'),
        ),
    ]
