# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20180806_0949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
