# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0008_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAdminCancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('1', '涉及非法内容'), ('2', '广告'), ('3', '色情暴力'), ('9', '其他')], help_text='所属分类', max_length=2, null=True, verbose_name='所属分类')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('message', models.TextField(blank=True, help_text='操作日志', null=True, verbose_name='操作日志')),
                ('order', models.ForeignKey(blank=True, help_text='所属订单', null=True, on_delete=django.db.models.deletion.CASCADE, to='order.OrderInfo', verbose_name='订单')),
                ('user', models.ForeignKey(blank=True, help_text='操作用户', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '订单管理取消表',
                'verbose_name_plural': '订单管理取消表',
            },
        ),
    ]
