# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderadmincancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='is_hot',
            field=models.BooleanField(default=False, help_text='热门订单', verbose_name='热门订单'),
        ),
    ]
