# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_orderinfo_is_hot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='deposit',
            field=models.PositiveIntegerField(default=0, help_text='押金(分)', verbose_name='押金'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_cost',
            field=models.PositiveIntegerField(default=1, help_text='雇主实付金额(分)', verbose_name='实付金额'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='reward',
            field=models.PositiveIntegerField(default=1, help_text='佣兵应得赏金(分)', verbose_name='佣金'),
        ),
    ]
