# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20180824_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='complete_time',
            field=models.DateTimeField(blank=True, help_text='订单完成时间', null=True, verbose_name='订单完成时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='description',
            field=models.TextField(blank=True, help_text='订单详细信息', null=True, verbose_name='订单详细信息'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='employer_complete_time',
            field=models.DateTimeField(blank=True, help_text='雇主确认完成时间', null=True, verbose_name='雇主确认完成时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='employer_receive_mobile',
            field=models.CharField(blank=True, help_text='联系人手机号', max_length=15, null=True, verbose_name='联系人手机号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='employer_receive_name',
            field=models.CharField(blank=True, help_text='联系人姓名', max_length=30, null=True, verbose_name='联系人姓名'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='from_addr',
            field=models.CharField(blank=True, help_text='任务地点', max_length=128, null=True, verbose_name='任务地点'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='from_time',
            field=models.DateTimeField(blank=True, help_text='任务开始时间', null=True, verbose_name='任务开始时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='privacy',
            field=models.TextField(blank=True, help_text='订单隐私信息', null=True, verbose_name='订单隐私信息'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='receiver_complete_time',
            field=models.DateTimeField(blank=True, help_text='佣兵确认完成时间', null=True, verbose_name='佣兵确认完成时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='receiver_confirm_time',
            field=models.DateTimeField(blank=True, help_text='佣兵接单时间', null=True, verbose_name='佣兵接单时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='receiver_user',
            field=models.ForeignKey(blank=True, help_text='佣兵', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to=settings.AUTH_USER_MODEL, verbose_name='佣兵'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='school',
            field=models.ForeignKey(blank=True, help_text='订单所在学校', null=True, on_delete=django.db.models.deletion.CASCADE, to='area.School', verbose_name='订单所在学校'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='to_addr',
            field=models.CharField(blank=True, help_text='交付地点', max_length=128, null=True, verbose_name='交付地点'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='to_time',
            field=models.DateTimeField(blank=True, help_text='任务结束时间', null=True, verbose_name='任务结束时间'),
        ),
    ]
