# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayOrder',
            fields=[
                ('id', models.CharField(help_text='支付订单编号', max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='支付订单编号')),
                ('order_type', models.PositiveSmallIntegerField(choices=[(1, '押金'), (2, '加赏'), (3, '佣金')], help_text='支付类型', verbose_name='支付类型')),
                ('pay_method', models.PositiveSmallIntegerField(choices=[(1, '支付宝'), (2, '微信支付'), (3, '余额')], help_text='支付方式', verbose_name='支付方式')),
                ('pay_cost', models.PositiveIntegerField(help_text='支付金额(分)', verbose_name='支付金额(分)')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '未付款'), (2, '付款确认中'), (3, '已付款'), (4, '已退款'), (5, '支付超时')], default=1, help_text='支付状态', verbose_name='支付状态')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='支付创建时间', verbose_name='支付订单创建时间')),
                ('expire_time', models.DateTimeField(help_text='支付订单过期时间', null=True, verbose_name='支付订单过期时间')),
                ('pay_time', models.DateTimeField(help_text='支付时间', null=True, verbose_name='支付时间')),
                ('order', models.ForeignKey(help_text='所属订单', on_delete=django.db.models.deletion.CASCADE, to='order.OrderInfo', verbose_name='所属订单')),
            ],
        ),
    ]
