# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paycenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorder',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '未付款'), (2, '付款确认中'), (3, '已付款'), (4, '已退款'), (5, '支付超时')], default=1, help_text='支付状态', verbose_name='支付状态'),
        ),
    ]
