# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='地点', max_length=32, verbose_name='地点')),
                ('detail', models.CharField(blank=True, help_text='详细地点', max_length=32, null=True, verbose_name='详细地点')),
                ('latitude', models.CharField(help_text='纬度', max_length=32, verbose_name='纬度')),
                ('longitude', models.CharField(help_text='经度', max_length=32, verbose_name='经度')),
                ('geohash', models.CharField(blank=True, help_text='geohash', max_length=12, null=True, verbose_name='geohash')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活', verbose_name='是否激活')),
                ('weight', models.IntegerField(default=1, help_text='权重', verbose_name='权重')),
            ],
            options={
                'verbose_name': '地址',
                'verbose_name_plural': '地址',
                'ordering': ('-weight',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='市')),
            ],
            options={
                'verbose_name': '市',
                'verbose_name_plural': '市',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='城市')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.City', verbose_name='市')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='省份')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='学校/区域', max_length=32, verbose_name='学校/区域')),
                ('latitude', models.CharField(help_text='纬度', max_length=32, verbose_name='纬度')),
                ('longitude', models.CharField(help_text='经度', max_length=32, verbose_name='经度')),
                ('geohash', models.CharField(blank=True, help_text='geohash', max_length=12, null=True, verbose_name='geohash')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活', verbose_name='是否激活')),
                ('weight', models.IntegerField(default=1, verbose_name='权重')),
                ('district', models.ForeignKey(help_text='所属区', on_delete=django.db.models.deletion.CASCADE, to='area.District', verbose_name='区')),
            ],
            options={
                'verbose_name': '学校/区域',
                'verbose_name_plural': '学校/区域',
                'ordering': ('-weight',),
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.Province', verbose_name='省'),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.ForeignKey(help_text='所属区', on_delete=django.db.models.deletion.CASCADE, to='area.District', verbose_name='区'),
        ),
    ]
