# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_auto_20180419_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='学校', max_length=32, verbose_name='学校')),
                ('latitude', models.CharField(help_text='纬度', max_length=32, verbose_name='纬度')),
                ('longitude', models.CharField(help_text='经度', max_length=32, verbose_name='经度')),
                ('geohash', models.CharField(blank=True, help_text='geohash', max_length=12, null=True, verbose_name='geohash')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活', verbose_name='是否激活')),
                ('weight', models.IntegerField(default=1, verbose_name='权重')),
                ('city', models.ForeignKey(help_text='所属市', on_delete=django.db.models.deletion.CASCADE, to='area.City', verbose_name='市')),
                ('district', models.ForeignKey(help_text='所属区', on_delete=django.db.models.deletion.CASCADE, to='area.District', verbose_name='区')),
            ],
            options={
                'verbose_name': '学校',
                'verbose_name_plural': '学校',
                'ordering': ('-weight',),
            },
        ),
    ]
