# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0004_auto_20180620_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='detail',
            field=models.CharField(blank=True, help_text='详细地点', max_length=32, null=True, verbose_name='详细地点'),
        ),
    ]
